name: Integration Tests

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: jruby:9.2.8
    steps:
    - uses: actions/checkout@v1
    - name: Install git
      run: |
        apt-get update
        apt-get install -y --no-install-recommends git
    - name: Install deps and run RSpec
      run: script/cibuild
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: gem
        path: logstash-output-prometheus-0.1.2.gem
  end-to-end:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download gem
      uses: actions/download-artifact@v1
      with:
        name: gem
    - name: Build docker image
      run: |
        cp gem/*.gem .
        docker build -f .github/Dockerfile -t logstash-output-prom:dev .
    - name: Test Plugin
      run: |
        docker run -d -p 9640:9640 logstash-output-prom:dev -f /config.test
        sleep 30
        curl localhost:9640/metrics > output
        cat output
        cat output | grep 'mycounter{value="hi"} 1.0'