name: Ruby

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jruby:9.2.8
    steps:
    - uses: actions/checkout@v1
    - name: Install git
      run: |
        apt-get update
        apt-get install -y --no-install-recommends git
    - name: Install deps and run RSpec
      run: script/cibuild
